#!/bin/bash

# if any commands on my codes fails for any reason, the entire shell script fails
set -o errexit

# fail exit if any of the pipe commands fails  
set -o pipefail

# exist if any of the variables is not set
set -o nounset

postgres_ready(){
python << END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${PG_HOST}",
        port="${PG_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
 >&2 echo "Waiting for postgreSQL to become available....:-("
 sleep 1
done
 >&2 echo "PostgreSQL is ready!!!!...:-)"

exec "$@"