#!/bin/bash

# if any commands on my codes fails for any reason, the entire shell script fails
set -o errexit

# fail exit if any of the pipe commands fails  
set -o pipefail

# exist if any of the variables is not set
set -o nounset

python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
python3 manage.py runserver 0.0.0.0:8000